name: ldm
channels:
  - pytorch
  - defaults
  - conda-forge
  - fastai
dependencies:
  - git
  - python=3.8.5
  - pip=22
  - cudatoolkit=11.6
  - pytorch=1.12
  - torchvision=0.13
  - numpy=1.22
  - albumentations=0.4
  - imageio=2.21
  - omegaconf=2.2
  - python-slugify=6.1
  - pip:
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.7.4
    - test-tube>=0.7.5
    - streamlit>=1.12.2
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.21.3
    - torchmetrics==0.9
    - kornia==0.6
    - gradio==3.2
    - accelerate==0.12.0
    - pynvml==11.4.1
    - basicsr>=1.3.4.0
    - facexlib>=0.2.3
    - -e git+https://github.com/CompVis/taming-transformers#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP#egg=clip
    - -e git+https://github.com/TencentARC/GFPGAN#egg=GFPGAN
    - -e git+https://github.com/xinntao/Real-ESRGAN#egg=realesrgan
    - -e git+https://github.com/hlky/k-diffusion-sd#egg=k_diffusion
    - -e .
